### ISSUE TITLE
Timeout errors in test-app.

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#217]
Please do work for this task in a branch called issue-217.

Sometimes I get "Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves." for some of the test-apps.

We should either set the timeout longer and ensure we are calling done() or make the test shorter.

**Comment by gcalica** [comment]
Honestly I've always had the problem of getting those timeout errors for both test and test-app since the first time I've run tests last summer. It's like a percentage chance for me; if I run the tests more than enough times I don't get any timeout errors, sometimes I do get them. 

I've always kind of just ignored those errors as I've always thought it might just be hardware on my side. Because I remember when I kept getting constant timeout errors running tests, I asked either Glen/Mercedez/Quinne to run the tests instead on their computer and they never really got the timeout errors, so I figured it might just my laptop. 

Should I be ignoring them or actually trying to address them?
