### ISSUE TITLE
Review: Landing, Student Home Page UI and Code

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#369]
## Overview

Welcome to the first UI-oriented review of RadGrad. The review process is still a work in progress, so feel free to suggest changes or improvements.  

In this review, we will study the user interface for the RadGrad2 Landing page, the Student Home Page, and the "subpages" associated with the Student Home Page (aboutme, ice, levels, log).  We will also look at the code used to implement those pages so that we get a "wholistic" view. 

I've made a slide show to illustrate the pages to be reviewed [here](https://docs.google.com/presentation/d/1lpNURsj0DPk4qPe2icLxhG_byFpvS36-sxd8PQwcQiA/edit?usp=sharing). 

You will want to login to radgrad2.ics.hawaii.edu as the opq student in order to display these pages on your laptop, and review the code in the branch indicated below.

## Review Branch

* https://github.com/radgrad/radgrad2/tree/review-369

## UI Pages to review

* https://radgrad2.ics.hawaii.edu/#/
* https://radgrad2.ics.hawaii.edu/#/student/opq@hawaii.edu/home/aboutme
* https://radgrad2.ics.hawaii.edu/#/student/opq@hawaii.edu/home/ice
* https://radgrad2.ics.hawaii.edu/#/student/opq@hawaii.edu/home/levels
* https://radgrad2.ics.hawaii.edu/#/student/opq@hawaii.edu/home/log

## Files to review

* https://github.com/radgrad/radgrad2/blob/review-369/app/imports/ui/pages/landing/LandingHomePage.tsx
* https://github.com/radgrad/radgrad2/blob/review-369/app/imports/ui/pages/student/StudentHomePage.tsx
* https://github.com/radgrad/radgrad2/blob/review-369/app/imports/ui/pages/student/StudentAboutMePage.tsx
* https://github.com/radgrad/radgrad2/blob/review-369/app/imports/ui/pages/student/StudentIcePage.tsx
* https://github.com/radgrad/radgrad2/blob/review-369/app/imports/ui/pages/student/StudentHomeLevelsPage.tsx

Since I am proposing for us to delete the Advisor Log page and its functionality, we won't review that code.

## Checklists

* [Design](https://www.radgrad.org/docs/developers/checklists/design-checklist)
* [User Interface](https://www.radgrad.org/docs/developers/checklists/ui-checklist)
* [JS and TS](https://www.radgrad.org/docs/developers/checklists/js-ts-checklist)
* [React](https://www.radgrad.org/docs/developers/checklists/react-checklist)

## Due date

Tuesday, Jan 19, 3:30pm

## Documentation

The review process is documented at: https://www.radgrad.org/docs/developers/reviews/overview

**Comment by hannaparkUH** [comment]
https://docs.google.com/presentation/d/10pyqnPpVWrkqKFmDho9XREZQ5T1s60_vVuCUXdJCCWU/edit?usp=sharing

**Comment by jatinp101** [comment]
**Does this present a good overview of RadGrad?**
This presents a good overview of Radgrad it presents the purpose of Radgrad, what students are supposed to get from using the software. It lets students know Radgrad’s feature set.
**Does it make it clear what to do next?**
When reaching the bottom of the page there is a call to action of users based on their affiliation whether they are a student, professor, or advisor. 
**Are there any “hidden” links? If so, how could these be made more visible?**
There are three hidden links one for career goals, interests, and opportunities. Possibly adding a line underneath could help make the link more visible. Another option is to turn those into buttons.
**Is the rotating set of images appropriate? What information does it convey? Could something more useful be displayed instead?**
I think the rotating set of images can be inspiring for students as it shows this can be “you” if you keep at the CS journey and if you do all these activities you can do well. But I think it would be helpful to show alumni with their positions at different top companies and showing their scores for Radgrad if that is allowed.
**Is the layout appropriate everywhere on the page?** 
In the “ready to get started” section I feel that the images should be centered rather than left-aligned.

**Comment by philipmjohnson** [comment]
## https://radgrad2.ics.hawaii.edu/#/

* Making Career Goals labels into a link is an Easter Egg. Plus not consistent: Students, Faculty, Alumni is not. Figure out a way to make the link obvious and visible.

* Can we provide better/more useful images for the rotating gif of people and points?

* "Ready to get started" panes are not centered.

* "Contact us" link at the bottom is broken. Delete?

* "RadGrad @ 2020". "@" is not copyright. Delete?

* Guided Tours button. Necessary? The landing page is not that big.

* "Ready to get started?" -> "Take these guided tours to learn more"

* Pictures are very ICS specific.

## https://radgrad2.ics.hawaii.edu/#/student/opq@hawaii.edu/home

* A deluge of text and boxes! It looks overwhelming.

* The top-level carousel: will people actually click the arrow? Could subsequent information be placed on pages where the user can actually interact with it?

* The three boxes talk about opportunities, courses, and career goals. What about interests? Could these be redesigned into four boxes that describe what they are and why you want them, what your current favorites are, and a button to change them?

* What is the goal of the home page?

* Move videos to its own page, listed on menubar?

* Rethink menubar organization. (See POST 307C whiteboard)

* When there are no favorites, the "recommended courses and opportunities" is empty. Could we have some defaults to that this area is never empty?

* In the new opportunities section, it's not clear that more info is available. Maybe make a button "Learn more" or something rather than making the title a link?

## https://radgrad2.ics.hawaii.edu/#/student/opq@hawaii.edu/home/aboutme

* This feels like to opposite of the home page: almost nothing here!

* Could we integrate most/all of this into the home page and/or top menubar?

* Can the information be presented a little more compactly? Two columns?

* "Share your information with others" needs a lot more explanation!

* Email is shared with others no matter what. Perhaps we need students to "opt-in" the first time they login to say that they agree to sharing their email address with other registered users.

* "My favorites". Why do this? What is the purpose of creating favorites?

* "View more"? Does that mean view more favorites? Or view more career goals?

## https://radgrad2.ics.hawaii.edu/#/student/opq@hawaii.edu/home/ice

* Way too much text. Needs a redesign.

## https://radgrad2.ics.hawaii.edu/#/student/opq@hawaii.edu/home/levels

* Duplicate information on levels. Needs a redesign.

## https://radgrad2.ics.hawaii.edu/#/student/opq@hawaii.edu/home/log

* Delete this page.

<hr/>

## LandingHomePage.tsx

* L73: Maybe use a string to indicate role, not an icon (never even noticed the icon was different)

## StudentHomePage.tsx
* L31: Rename StudentPageMenuWidget to StudentPageMenu.* L32: Rename GuidedTourStudentHomePageWidget to GuidedTourStudentHomePage* L64: filter().length?* L66: Do we still need withTracker if there are no subscriptions? (I genuinely don't know).

## StudentAboutMePage.tsx
* L10-31: Collapse to one line.* L45: I need to understand when we need withTracker.

## StudentIcePage.tsx

* OK

### StudentHomeLevelsPage.tsx
* L175: What if we stored the number of students at each level in public stats?  Then we wouldn't need to access student profiles, we could just show the number. 

More general design question: given that students don't normally provide a profile picture, and given FERPA privacy issues, how should we design the UI? Should we design around "aggregate" information, in which case it could be in public stats?

**Comment by cammoore** [comment]
Landing Home Page UI

 * Add the word explore or something like that for the links to career
   goals, interests, opportunities.

 * I don't like the rotating cards. We don't display students like
   that anywhere in RadGrad.

 * The three guided tours aren't centered on the page and it looks
   like there is a missing tour. Which is true.

 * I think there needs to be some text saying login or send an email
   to the admin to register for RadGrad.

 * Ready to get started? is miss leading since it is just a guided
   tour. Maybe have the last slide of the guided tour visible on the
   page? 

 * Guided tour in mobile is terrible. Return to RadGrad not obvious.

LandingHomePage.tsx

 * L17-20, names of the properties are missleading. They are counts.

 * React-O6: L75-78, These should be consts.

Student Home Page UI

 * With no interests or career goals this page doesn't make sense. Why
   is there a header for RECOMMENDED COURSES & OPPORTUNITIES, but
   there aren't any.

 * How can we get Ophelia to select some interests and career goals
   from this page. Once she does we should change the page so she sees
   the recommendations.

 * Change the menu bar. Maybe make it like on the board in the office?

 * Lots of white space below the videos.

StudentHomePage.tsx

 * TS L14, L20, Why are we using match shouldn't we be using the
   react-router-dom hooks? Update buildExplorerRoute.

 * TS L21, The type is incorrect it should be { interestID:
   string, count: number }[]

 * TS L22 - 24, why aren't they all the same type?

 * JS L25 and 29, ready is declared but not used.

 * JS L67, why use key?

 * JS-06 L77, use favIDs.forEach.

Student About Me Page UI

 * Too much white space

 * Not sure what to do. View more is not enough info. Maybe a little
   text explaining the sections. 

 * Don't like the section titles. About me is just name and picture?

 * Menubar in mobile is busted. Only see a few options.

 * Why so much white space in mobile?

StudentAboutMePage.tsx

 * React L29-37, We're using a container why pad the Grid.Row with two
   Grid.Columns?
 
Student Ice Page UI

 * What's the deal with ICE is duplicated twice on the page at the top
   and at the bottom.

 * Is there a way to show and hide the help panel. Maybe remember the
   state in a collection?

 * The Get to 100 suggestions are not good since Ophelia has so few
   interests. May want to update the text when they have too few
   interests. 

 * Menubar on mobile. White space.

StudentIcePage.tsx

 * JS L10, L12, Why new lines?

 * REACT-06 L58, helpMessages isn't typed.

Student Levels Page UI

 * Why so much white space to the right of the levels in Help Message?

 * Why repeat the boxes, but with different information?

StudentHomeLevelsPage.tsx

 * JS-01: The name of the file and class doesn't need 'Home'.

 * REACT: L31 - 155, should this be a React component?

 * REACT-06: L188, L190, should be typed.

**Comment by RashmiAR** [comment]
1. In the RadGrad home page, align Ready to Get Started
2. Alignment of text under icons in Why Use RadGrad
3. In Student Home Page, it says Recommended Courses and Opportunities(but there is no content)
4. Empty bottom left portion in student home page, is it because we are not displaying anything for Recommended Courses and Opportunities.
5. In student/home/aboutme page should we add favorite opportunities and courses which are marked as favorites from StudentDegreePlanner.
6. Student/home/ice page in development environment is different from radgrad2.ics.hawaii.edu( The ICE circle explained is repeated twice)
7. In Student/home/levels page, levels are repeated(aligned horizontally and vertically). But in development environment its not repeated.
8. In /ui/pages/student/StudentHomeIcePage.tsx, remove empty lines at line 10 and 12

**Comment by philipmjohnson** [comment]
## Landing Page action items

* Make rotating images more useful. 
* Guided Tours don't help you get started. 
* Remove easter egg links
* How can we take the five actions in "Why Use RadGrad" and concretely illustrate how there is support for each of them. 

## Home Page

* Provide a useful page when a UH person uses CAS to login but they are not part of the system. Currently they might end up on the landing page? 

* Overwhelmed by all the stuff that's going on. 
* Help page doesn't provide useful information.
* Carousel: no one will click it. 
* Page could be "smart" about the status of the student. 
* Home Page could be like a "mission control" for student.
* Change "Favorites" to "Your Interests", etc.
