### ISSUE TITLE
Intermittent "No profile found" error when retrieving/refreshing pages.

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#382]
Please do work for this task in a branch called issue-382.

Let's say you're in any page of RadGrad2, such as career goals:

<img width="1286" alt="Screen Shot 2021-02-05 at 1 36 18 PM" src="https://user-images.githubusercontent.com/290288/107100004-3a511300-67b7-11eb-8a09-dd7d82350c6e.png">

Now refresh the page. Instead of seeing the page contents again, you get a page not authorized error:

<img width="1286" alt="Screen Shot 2021-02-05 at 1 36 50 PM" src="https://user-images.githubusercontent.com/290288/107100044-4c32b600-67b7-11eb-8245-21fe46be17a2.png">

You can click the RadGrad icon to get to the landing page, whereupon there is a "Student Home" button to get you to the home page, whereupon you can get back to the Career Goals page, but that is certainly not something we want users to have to do.

**Comment by cammoore** [comment]
My understanding of what is going on is:

 * Reloading the page didn't allow for the subscriptions to run. I put console.logs and the withTracker wasn't running on the reload. I don't know why.
 * Since the subscriptions weren't finished looking up the Student's Profile fails and the loggedInUsername doesn't match and we say you are not authorized to view your page.
 * I added a Redirect back to the LandingHomePage with a state set to the current page.
 * Updated LandingHomePage to look at the location.state and Redirect back if the state is set. This allows all the subscriptions to run and we see the page.

Not sure if this is the best solution, but it works.

**Comment by philipmjohnson** [comment]
Unfortunately, this problem does not appear to be completely fixed. Refreshing regularly (but not always) leads to something like this:

<img width="970" alt="Screen Shot 2021-02-08 at 11 32 10 AM" src="https://user-images.githubusercontent.com/290288/107284175-75df1d80-6a01-11eb-90f8-1506d92a4a0e.png">

**Comment by cammoore** [comment]
I can't reproduce this.

**Comment by philipmjohnson** [comment]
Here's maybe a related problem? From the deployed version of RadGrad2:

<img width="1327" alt="Screen Shot 2021-02-08 at 2 50 59 PM" src="https://user-images.githubusercontent.com/290288/107300244-37eff280-6a1d-11eb-954d-4a200ce16224.png">

**Comment by cammoore** [comment]
You need to update the settings.development.json and settings.production.json files adding the following properties to the public group.

    "tagline": "Developing awesome _computer scientists_, **ONE** graduate at a time.",
    "landingSubject": "Computer science",
    "instanceName": "UHM/ICS",
    "userGuideURL": "https://www.radgrad.org/docs/users/"

**Comment by cammoore** [comment]
Going to move this to To do.

**Comment by philipmjohnson** [comment]
I think I've found a way to reproduce this.  

  1. In the master branch, run RadGrad2, login as the admin user. 
  2. Click on any user in the Admin's home page.  For me, at least, I get the "No profile found" error.
  3. If you logout, you can login as that user without a problem.

**Comment by cammoore** [comment]
The admin click on student issue was caused by the LandingHomePage not subscribing to the AdminProfiles collection.
