### ISSUE TITLE
1. Perform critical review of RadGrad documentation

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#465]
Please read through the entire RadGrad documentation site at https://radgrad.org.

As you read, please identify areas in which the documentation could be clarified or improved.

Post your ideas as a comment to this issue.

Since reviewing the documentation site will likely take several sessions, you should post your comment at the end of each session, then edit that comment body during a subsequent session. That way, each developer's ideas will be consolidated in a single comment, even though that comment will be incrementally built over several sessions of work.

**Comment by trey-sumida** [comment]
1. Personally I feel like the "Getting started" page should come after "Why RadGrad?" in the User Guide/Students navigation. This way users can get a general feel for the website, and view the subsequent sections after to gain a better understanding of each feature.

**Comment by saitoshi** [comment]
<b>Initial Comment</b>
I really like how the contents or the overview is broken up and how it includes a small description within what each page should have. I think the codes that should be used are written in clear format too. 
<b> Personal Comments </b>
<ul>
<li> On the Tech Stack page for the section covering Intellij Idea where it was talking about importing "ics-se-code-style", the Intellij Idea had "Code Style" rather than "Coding Style". Small but thought it was worth mentioning. 
<li>  The green colored font, when its in light mode is a little hard to read. Would it be possible to make the green color darker. 
</ul>

**Comment by timothyhuo1** [comment]
1. Overview | Basic Constructs | Under Career Goals - I was a bit confused when it says "the system will notify Advisors and Faculty if there are Interests present which students have no ability to investigate further."

**Comment by ruizaj** [comment]
**Comments**
- I've noticed that one of the goals is to increase diversity of students in computer science through the usage of the site. Perhaps this could be elaborated on the approach as usually only ICS/CENG students would be the only ones to know about RadGrad. It is also possible to gauge diversity with retention as well since they heavily correlate, especially with first-year students.
- I didn't notice that the sections on the right side had hyperlink functionality unless you hover over it. Perhaps making it more noticeable by increasing font size.

**Comment by CalianaFortin** [comment]
## First Session: 

### Overview | Motivation:
Overall this sections is good. I like that is overall short and concise. These are just a few flow/grammatical errors which could be fixed.
- In this section I was initially confused with the term _first class_ status. I think it probably could be replaced with the word _prioritizes_. 
> To combat this, RadGrad provides students with a faculty-curated knowledge base of discipline-specific "Interests" ~and~, "Career Goals", and which curricular and extra-curricular activities will help students learn more about them. 
- The wording in this sentence could be improved by removing the _and_ after “Interests” and replacing it with a comma.
>The design of RadGrad is influenced by research on diversity ~and~, retention and two educational research theories:
- Remove the _and_ after retention and replace with a comma. 

### Overview | Goals:

Again, overall this section is good. This is just a flow/grammatical error which could be fixed.

> We hypothesize that by providing access to the diversity of applications of computer science… 
- This sentence could be improved by writing _to the diversity of computer science applications …_ 

### User Guide | Students | Verification Requests:

- Verification Requests in the Students section I think should be moved after the Opportunities section since it is associated with the Opportunities topic.

**Comment by philipmjohnson** [comment]
Thanks for your insightful comments!  I made the above fixes to the documentation.
