### ISSUE TITLE
Review: ManageReviewsPage and components.

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#532]
## Overview

We'll be reviewing the `ManageReviewsPage` and its components.

## Review Branch

[review-532](https://github.com/radgrad/radgrad2/tree/review-532)

## Files to review

* [ManageReviewsPage.tsx](https://github.com/radgrad/radgrad2/blob/review-532/app/imports/ui/pages/shared/ManageReviewsPage.tsx)
* [ModerationWidget.tsx](https://github.com/radgrad/radgrad2/blob/review-532/app/imports/ui/components/shared/moderation/ModerationWidget.tsx)

## Checklists

* [Architecture](https://www.radgrad.org/docs/developers/checklists/architecture-checklist)
* [Design](https://www.radgrad.org/docs/developers/checklists/design-checklist)
* [User Interface](https://www.radgrad.org/docs/developers/checklists/ui-checklist)
* [JS and TS](https://www.radgrad.org/docs/developers/checklists/js-ts-checklist)
* [React](https://www.radgrad.org/docs/developers/checklists/react-checklist)

## Due date

Thursday, May 27th, 11:30 am.

## For more information

The review process is documented at: https://www.radgrad.org/docs/developers/reviews/overview

**Comment by philipmjohnson** [comment]
## ManageReviewsPage.tsx

* Use export default withTracker(...). (Get rid of Container declaration).

* Why not inline the AdminModerationWidget code into this page? In general, if a page only contains a single component that is not used anywhere else, then consider putting that code directly into the page. 

* (Note that this page imports AdminModerationWidget, but it's actually ModerationWidget, since the page will be available to
  Faculty and Advisors as well).

## ModerationWidget

* We don't use "Widget" suffix anymore. Could just be "Moderation".

* Why define handleAcceptReview and handRejectReview in this component? Why not define them in ModerationColumnWidget?

* As noted above, this component can be deleted an inlined into ManageReviewsPage.

## ModerationColumnWidget

* isReview is always true, so we can delete this parameter.

* Use RadGradSegment, not `<div><Segment><Header>...`.

* Can we ever display a ModerationQuestionCard? It requires isReview to be false, but I don't see a code path where isReview is false.

## ModerationReviewCardWidget

* Would using AutoForm make the form clearer or simpler or more  correct?

**Comment by trey-sumida** [comment]
**ManageReviewsPage.tsx**
REACT-06: Define typed constants in withTracker().
- opportunityReviews and courseReviews are not defined as typed consts first and are immediately returned 

REACT-09: Imported component names and file names should match
- Line 6 “AdminModerationWidget” is doesn’t match the filename “ModerationWidget”

**ModerationWidget.tsx**
Design-01: Can you refactor to reduce duplication?
- Is it possible to combine the handleAcceptReview and handleRejectFunction into one?

REACT-10: Avoid "Widget" and "Card" in component names
- Component is named “ModerationWidget”

TS-01: Avoid any.
- Line 12, 23 "item" and "comments" arguments have “any” type. Not sure if this is necessary for the function to work.

**Comment by timothyhuo1** [comment]
ManageReviewsPage.tsx

- REACT-06: L22, L23: put the properties in a return using object shorthand 
- REACT-09: exported component and file name do not match

ModerationWidget.tsx

- Design-01: L12-L21, L23-L32: code looks similar, possibly refactor 
- Design-05: L13,L14, L24, L25: unnecessary comments 
- REACT-10: avoid “widget” in the name of the component

**Comment by CalianaFortin** [comment]
### ManageReviewspage.tsx
**REACT-06: Define typed constants in withTracker()**

- I think there should be constants and a return statement returning the properties. 

### ModerationWidget.tsx

**REACT-10: Avoid "Widget" and "Card" in component names**
- The file should be renamed to Moderation.tsx  . 

**Design-05: Ensure comments are appropriate.**
- Are the comments on lines 13 and 24 needed?

**Comment by saitoshi** [comment]
<h4>ModerationWidget.tsx</h4>
<ul>
<li> Design 05 Comments</li>
Line 13-14 and Line 24-25 has comments that
<li> React 10 Avoid :Widget" in the component names </li>
The name contains the word Widget
</ul>
<h4> ManageReviewPage.tsx</h4>
<ul>
<li>  React 06: Define typed constants in withTracker()</li> 
I think that there should be consts and return statement 
</ul>

**Comment by cammoore** [comment]
ManageReviewsPage.tsx

RE-09: L6 Imported component names should match filename
RE-10: L6 Avoid Widget
https://github.com/radgrad/radgrad2/blob/ab56f2c60e9a103f34cc15f98c5e7be4b79ee8e6/app/imports/ui/pages/shared/ManageReviewsPage.tsx#L6
RE-06: L21-24 Define typed constants
https://github.com/radgrad/radgrad2/blob/ab56f2c60e9a103f34cc15f98c5e7be4b79ee8e6/app/imports/ui/pages/shared/ManageReviewsPage.tsx#L21-L24


ModerationWidget.tsx

RE-10: L5 Avoid Widget
https://github.com/radgrad/radgrad2/blob/ab56f2c60e9a103f34cc15f98c5e7be4b79ee8e6/app/imports/ui/components/shared/moderation/ModerationWidget.tsx#L5
JS-07: L13-14, 24-25 Avoid console.logs

L12 - 32: Doesn't do anything.
https://github.com/radgrad/radgrad2/blob/ab56f2c60e9a103f34cc15f98c5e7be4b79ee8e6/app/imports/ui/components/shared/moderation/ModerationWidget.tsx#L12-L32

**Comment by ruizaj** [comment]
ManageReviewsPage.tsx

Architecture:
- Arch-02 AdminModerationWidget should be within the bracket as well of its import.

Design:
- Design-01 Making ManageReviewsPageContainer a const, but then exporting it right after is redundant. 
- Design-07 headerPaneBody uses too many lines, can remove excess lines. Replace ` with '

React:
- React-09 Imported ModerationWidget instead of ModerationWidgetProps, so it's using the interface instead of the export default.

ModerationWidget.tsx

Architecture:
- Arch-03 Imported files from the wrong directories causing errors.

Design:
- Design-04 Excessive comment blocks, need to remove.
- Design-01 Duplicated code of handleAcceptReview and handleRejectReview, can merge those two together in some way.
- Design-01 Interface is redundant as both opportunityReviews and courseReviews uses the same collection.
- handleAcceptReview and handleRejectReview can be defined within export defaults to reduce clutter.

Javascript/Typescript:
- ESLint-01 errors from importing from wrong directories.

React:
- React-10 Change component name to remove 'widget'.
- React-09 Export isn't used at all outside of the component.
