### ISSUE TITLE
HelpPanelWidget

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#6]
Please do work for this task in a branch called issue-6.

The HelpPanelWidget doesn't behave like the RadGrad1 Help_Panel_Widget.

**Comment by gcalica** [comment]
[ui/components/shared/HelpPanelWidget.tsx#L38](https://github.com/radgrad/radgrad2/blob/ad7510d1dbad0adfe8ab2db3a3bcfe8c7047281f/app/imports/ui/components/shared/HelpPanelWidget.tsx#L38)
I think maybe this should just be a .findOne() instead of .findDoc(). I've had to deal with problems where, for example in the Generic Card Explorer Page which handles all the Card Explorer Pages, the HelpPanelWidget just straight up crashes everything since not all of the Card Explorer Pages have a HelpMessage defined for those pages and the fact that .findDoc() throws a Meteor.error if there is no defined HelpMessage. 

My temporary fix was just checking if there exists a helpMessage first before rendering it
```
public render() {
   const helpMessage = HelpMessages.findOne({ routeName: this.props.match.path });
   ...
   return (
      {
         helpMessage ? <HelpPanelWidget/> : ''
      }
   )
}
