### ISSUE TITLE
Fix Add Course Form

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#666]
Please do work for this task in a branch called issue-666.

The Add Course form is broken because it can't process Interest selections correctly:

<img width="1149" alt="Screen Shot 2021-06-18 at 1 23 45 PM" src="https://user-images.githubusercontent.com/290288/122623694-d1b55500-d038-11eb-8463-6c46b06da483.png">

Please fix this, and also review other Add forms to ensure they're OK.
.

**Comment by philipmjohnson** [comment]
I just deployed to radgrad2 and I am still getting errors when adding new courses:

<img width="1625" alt="Screen Shot 2021-06-21 at 1 14 06 PM" src="https://user-images.githubusercontent.com/290288/122838902-b3e32c80-d292-11eb-967f-e556889686b1.png">

Unlike before, the course does get successfully added even though errors are displayed. 

Also, if I try to add two courses in a row, the second add reliably fails.  Usually, but not always, if I refresh the data model page before doing the second add, things work OK.  Sometimes, but not always. 

Also, the accordian list of courses is not in alphabetical order by course name, which is confusing.

**Comment by cammoore** [comment]
* Updated the withTrackers for the Admin DataModel pages to sort the items.
* Added TestCafe tests for most of the Add Forms.
* Removed most of the `defineData = doc` statements since we often change the defineData (e.g. switching from names to slugs). This caused some of the validation errors.
* Added DayField and updated the Opportunity forms to use it.
* Updated the CourseCollection's findDoc to work with the getName value.
