### ISSUE TITLE
Review: InternAloha 

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#702]
## Overview

In this review, you will read through selected files of the InternAloha implementation.  The goal of this review is to:

1. Find opportunities for improvement in the InternAloha code base.
2. Learn how InternAloha system manipulates Internship data for presentation.
3. Develop a high-level design for the implementation of Internships in RadGrad.

## Preliminary activities

There is a fair amount of information you need to familiarize yourself with in order to perform an effective review of this implementation. 

### 1. Search for Internships manually

To understand what the scrapers do, there's no substitute for first trying to find Internship listings yourself. So, please spend a few minutes looking for internships at each of the following sites.  You may need to create accounts:

  * https://angel.co/.  We are currently getting around 900 listings from this site.
  * https://www.glassdoor.com.  We are also getting around 900 listings from here.
  * https://studentopportunitycenter.com/. We got about 1340 from here.

### 2. Review our Scraping results spreadsheet

To help understand the results of scraping over time and to detect problems, we maintain a spreadsheet at https://bit.ly/2SW3nha that contains three tabs at the bottom:
  * Num listings.  This page shows the total number of listings collected by each scraper on a given date.
  * Elapsed time. This page shows the total time (in minutes) required by each scraper.
  * Errors.  This page shows if any scraper generated an error. 

This data is useful to detect problems. For example, a scraper may change from generating 1000 listings to only generating 10, but still run to completion successfully.  A dramatic drop in listings indicates a problem with scraping regardless of whether the system ran without error or not. 

Do not make any entries in this spreadsheet as part of this review.  I include it to help you understand this issues involved with scraping internship data. 

### 3. Review InternAloha/RadGrad integration design issues

Next, please review [InternAloha Design Issues](https://www.radgrad.org/docs/developers/internaloha/design-issues).  This will help you understand what you are looking for as you review InternAloha code. 

### 4. Experience running the scrapers locally

Prior to review, it is important to be familiar with the results of running the code. For instructions on how to run scrapers, please read [InternAloha Scraper Developer Guide](https://internaloha.github.io/documentation/doc). The [InternAloha Site Management chapter](https://internaloha.github.io/documentation/docs/developers/site-management) provides additional information.

If you run into problems following this documentation, please post your comments and issues to the #internaloha-chat channel. Either Andre or Philip will reply to help you out, and update the documentation if necessary. (Making sure the scraper documentation is up to date is a useful and important outcome of this review.)

## Review Branch

Each person will want to create their own branch. Please call it `review-702-<name>`, where `<name>` is replaced by your first name (caliana, timothy, etc.)

You will use this branch to document your proposed design for integration of InternAloha into RadGrad.

## Files to review

The following file implements the CLI for InternAloha:
* https://github.com/internaloha/internaloha/blob/master/scraper/scrapers/main.js

The Angel List scraper:
* https://github.com/internaloha/internaloha/blob/master/scraper/scrapers/angellist.js

The GlassDoor scraper:
* https://github.com/internaloha/internaloha/blob/master/scraper/scrapers/glassdoor.js

Student Opportunity Center scraper:
* https://github.com/internaloha/internaloha/blob/master/scraper/scrapers/studentOpportunityCenter.js

## Checklists

* [Architecture](https://www.radgrad.org/docs/developers/checklists/architecture-checklist)
* [Design](https://www.radgrad.org/docs/developers/checklists/design-checklist)
* [JS and TS](https://www.radgrad.org/docs/developers/checklists/js-ts-checklist)
* [Combined](https://www.radgrad.org/docs/developers/checklists/combined)

## What to do

There are two parts to this review.

**1. Review InternAloha files, record your issues as a comment to this issue.**
Like a normal review, please take a look at these files and generate thoughts on how to improve them as a comment.

**2. Create a design for InternAloha/RadGrad integration.**
In your review branch, sketch out a design for how to perform Task 3 of the [InterAloha RadGrad Implementation Plan](https://www.radgrad.org/docs/developers/internaloha/design-issues#implementation-plan). 

You can do this design by creating files in your review branch with classes or functions.  You can use JSDoc or other comments to indicate what a function or class does.  But: No Implementation. This is a design. 

This will require several-to-many hours of your time. Spend a minimum of an hour, or as much as you want.

## Due date

Thursday, July 8

## For more information

The review process is documented at: https://www.radgrad.org/docs/developers/reviews/overview

**Comment by philipmjohnson** [comment]
## Main.js

https://github.com/internaloha/internaloha/blob/383a53292ec679cf42896a0114bdf8a3780fddfd/scraper/scrapers/main.js#L141
* can just say { apple, acm, ....}

## angellist.js

https://github.com/internaloha/internaloha/blob/383a53292ec679cf42896a0114bdf8a3780fddfd/scraper/scrapers/angellist.js#L67
  * Long strings, repeated. Would be good to make them string constants with descriptive names, then only need to edit one string (and reduces chances of typos).

## studentopportunitycenter.js

https://github.com/internaloha/internaloha/blob/6a9f196eaf51ef36c3875a6db43f0a8610029cfb/scraper/scrapers/studentOpportunityCenter.js#L16
  * That's just crazy. 


## General comments

I am starting to wonder if there is a more general structure to scrapers, like:

  * login()
  * findRelevantListings()
  * retrieveSingleListing()
  * parseListing()

Let's look at structure of the three parsers:

Angellist:
  * login()
  * getData(page)
  * startBrowser()
  * main()

GlassDoor
  * scrapeInfo(page...)
  * main()

Student Opportunity Center
  * getData(page)
  * main()

In addition, are there certain strings (i.e. CSS selectors) that are common to most scrapers? 

Can we create an abstract class that specifies the structure of a scraper, and then instantiate a subclass with specifics for a given scraper? 

Would that make it easier to understand, debug, and create new scrapers?

**Comment by trey-sumida** [comment]
**main.js**
DE-01: Can you refactor to reduce duplication?
Lines 142-159 can be shortened using object property shorthand

**angellist.js**
AR-01: Obey file name conventions
Some files are named in camel case while others are all lowercase, which should be the standard?

DE-07: Ensure code is readable
Consider adding comments to break down the code into “sections” detailing what a certain block of code does

DE-09: Ensure reusable code is exported or made available in the appropriate place
startBrowser is already a function other scrapers use located in the scraper-functions.js file, can it be standardized to use one or the other?

JS-09: When objects do not have any fields, use one line
Lines 34-35 should be one line

General Comments
Line 97 indentation is off

**glassdoor.js**
DE-01: Can you refactor to reduce duplication?
Lines 36, 37 can be moved to line 43 to look like:
Const [browser, page] = await startBrowser(headless);
Lines 20-31 code can be reduced using object property shorthand.
Lines 109-129 and 131-146 are very similar, could some or all of it be made into 1 function? If not, the breakOut variable is not needed for the second loop as line 142 can contain the break; statement there

DE-07: Ensure code is readable
Consider adding comments to break down the code into “sections” detailing what a certain block of code does

General Comments
Line 151 should be a part of line 150

**studentOpportunityCenter.js**
DE-01: Can you refactor to reduce duplication?
Lines 27, 28 can be moved to line 34 to look like:
Const [browser, page] = await startBrowser(headless);
Lines 84-94 can be shortened using object property shorthand

ES-01: No errors, avoid warnings
Lines 26, 51, 54, 62, 68 all have eslint disables. Can these be removed?

General Comments
Line 10, Search_SELECTOR should be renamed to SEARCH_SELECTOR to be consistent with other selector consts 

Scraper-functions should be in a utilities directory

**Comment by saitoshi** [comment]
<b>Main.js</b>
<ul>
<li>DE-02: Probably should avoid deeply nested conditional if possible</li>
<li>JS-05: Avoid Console.log: line 255,260,309,390 </li>
<li>JS-09: Use one line Layout: line 141, 
<li> Would it be possible to transfer some common structures making the main.js easier to follow through?</li>
</ul>
<b>AngelList.js</b>
<ul>
<li> AR-01: File name conventions: There is some mixed up namestyling so maybe we should adhere to a single convention </li>
<li> DE-09: Reusable Code to Exported: startBrowser is already a function located somewhere else </li>
</ul>
<b>StudentOpportunityCenter</b>
<ul>
<li> ES-01 Avoid Warnings: Line 26,51,54,62, 68 had eslint disabled. Is it possible to fix them?</li>
<li>JS-09 Use one line Layout: line 83 is it possible to write it out like that?</li>
</ul>
<b>GlassDoor</b>
<ul>
<li> DE-01: Can you refactor to reduce duplication: Line 36, 37</li>
<li>JS-09: Use one line Layout: line 20 </li>
</ul>

**Comment by CalianaFortin** [comment]
### Main.js:
function exportCVStoJSON
- is it intentional that it says CVS to JSON instead of CSV 

function convertToCVS
- is it intentional that it says CVS instead of CSV 

**AR-02: Obey directory structure**
- Is it possible to move where this file is located?
- maybe in a directory titled CLI 
- Currently it is in the scraper > scrapers  
- located with all the scraped even though it is not a scraper provides more of a general use for the scrapers though 

### Comment on the scrapers directory 
- tests should be in there own directory within the scrapers directory 
- multi-parser.js also appears to be a utility file so it should be in its own directory within the scrapers directory 

**function getData(page)**
- appears to be used in multiple scrapers. Is it possible to make it a utility function in a different directory

**The file scraper-functions.js** 
- this file appears to hold functions used in most of the scrapers 
- needs to be in its own directory 

Angellist:
* DE-01: Can you refactor to reduce duplication?
* DE-08: Ensure code is DRY
* DE-09: Ensure reusable code is exported or made available in the appropriate place.
 - Looking at other scrapers like 8000 hours and Acm
- why does one file import the functions  (fetchInfo, startBrowser, writeToJSON) from scraper-functions.js and the other file(s) (like Angellist and Acm) implement them 
- Comparing Angellist and linkedin why is the export functions different? 
- Why is the go to function not implemented in the linkedin scraper? 

GlassDoor:
* DE-01: Can you refactor to reduce duplication?
* DE-08: Ensure code is DRY
* DE-09: Ensure reusable code is exported or made available in the appropriate place.
 - comparing Angellist to Glassdoor: How is the scrape info function different from the get data function?
    - maybe standardize this function to be used for multiple files 

SOC:
* DE-01: Can you refactor to reduce duplication?
* DE-08: Ensure code is DRY
* DE-09: Ensure reusable code is exported or made available in the appropriate place.

- Again the same comment as Glassdoor 
    - the get data function is different from the others. Could this be standardized?

Why do we sometimes have a login in function in some files as opposed to others?
- Possibly make it an exportable function

**Comment by timothyhuo1** [comment]
AR-01: Obey file name conventions  

angellist.js
JS-06: L85: Avoid lodash functions (_.uniq)
L34: Could create a function similar to startBrowser from scraper function js to launch browser. Allow for different parameters (headless, devtools, slowmo)

studentOpportunityCenter.js
L26, L51, L54, L62, L68: unsure eslint disable next line
L10, L16 - L20, L45: Is it possible to grab the content by targeting the div[class] or other html tags? 

Maybe add more comments in the scrapers, to provide more information on what is going on

**Comment by cammoore** [comment]
main.js

Arrow functions?

L 188 name of the function convertToCVS typo.
L 268 name of the function exportCVStoJSON typo.

angellist.js

Arrow functions?
Why have startBrowser? There's a startBrowser in scraper-functions.

studentOpportunityCenter.js

I don't understand the for loops.

**Comment by ruizaj** [comment]
main.js:
- The optionDefinitions and the sections can be held inside a json file or a separate file to remove clutter.

angellist.js:
- L75-76 Uses a set amount of autoScrolls instead of making it a conditional depending on if there is more items to scroll down to or not. 
- Angellist generates a json file (angellist-urls.json) with all the urls within it, when the urls could be stored in an object list within the script itself.
- L90 can replace the writeFile functions with the one already made for the scrapers.

glassdoor.js:
- Breakout functionality might be neglegible since glassdoor doesn't really have a recaptcha system. This however could be useful if they do reimplement it later on.
- Scrapes info differently than most scrapers, so it can be changed to match the "getData" function commonality.

studentOpportunityCenter.js:
- Making consts for css selection is redundant and can just be done within the script. 
- getData doesn't reflect the scrapped data that it wants to scrape. It also holds data that internships don't need.
- Should be deleted since soc.js is the new SOC scraper.

Part 2:

Task 3: 
- Implementing data import systems will most likely start at internAloha as a script in main.js to combine all the json files together. 
- There's two options to approach in importing the data. One is downloading that combined.json manually and import the file into RadGrad, or make a function
called internImport.jsx to basically scrape the github page of the combined file and impend the data into our own json file. 
- If manually importing the combined.json file, we would need an internshipFilter.jsx to go through the file and filter out unnecessary listings.
- In terms of filtering out duplicates and useless listings, it'll be quite difficult as to a good solution to this. One would be filtering by position, company, and location since many listings have same names,
but different companies and vice versa. Duplicates from different sites is negligible since they most likely have different info and it'd be hard to catch.
- It's also a valid choice to filter out listings that don't have all the requirement info (including those that have only one or few N/A) since most people looking for internship would want all that information. This will
also significantly reduce the amount of listings to see, which can be a good idea.

**Comment by ruizaj** [comment]
**Andre's Design Branch**
https://github.com/radgrad/radgrad2/tree/review-702-andre/app/imports/api/internship
- Implementing data import systems will most likely start at internAloha as a script in main.js to combine all the json files together. 
- There's two options to approach in importing the data. One is downloading that combined.json manually and import the file into RadGrad, or make a function
called internImport() to basically scrape the github page of the combined file and impend the data into our own json file. 
- If manually importing the combined.json file, we would need an internshipFilter() to go through the file and filter out unnecessary listings.
- In terms of filtering out duplicates and useless listings, it'll be quite difficult as to a good solution to this. One would be filtering by position, company, and location since many listings have same names,
but different companies and vice versa. Duplicates from different sites is negligible since they most likely have different info and it'd be hard to catch.
- It's also a valid choice to filter out listings that don't have all the requirement info (including those that have only one or few N/A) since most people looking for internship would want all that information. This will
also significantly reduce the amount of listings to see, which can be a good idea.

**Comment by cammoore** [comment]
You can find my branch at https://github.com/radgrad/radgrad2/tree/review-702-cam

## General Design

### API
 * Add InternshipInstanceCollection.
 * Add ProfileInternshipCollection.
 * Add ValidatedMethods to get the InternAloha internships See https://github.com/radgrad/radgrad2/blob/review-702-cam/app/imports/api/internship/InternshipCollection.methods.ts for some comments.
 * Add utilities directory to internship directory. Define the InternAlohaScrapers enum. Helper functions to parse descriptions to find interest and career goal slugs. See https://github.com/radgrad/radgrad2/blob/review-702-cam/app/imports/api/internship/utilities/internship-utilities.ts for more comments.

### UI
 * Add ManageInternshipsPage for Admins and Advisors. Mostly for calling the validated methods to update the internship collection.

**Comment by trey-sumida** [comment]
Branch: [](https://github.com/radgrad/radgrad2/tree/review-702-trey)

I took inspiration from how matriculating students functions as what we are trying to accomplish seems similar in the sense that the UI (button) is just there to start the process which happens mostly on the server side.

I added a file in located at app/private/internaloha/scrapers.urls.txt which will store the github urls to the JSON files. The functions that relate to the import system are held in app/imports/api/internship/internshipCollection.methods.ts. We have a the large exported function uploadInternships, with a bunch of smaller helper functions.

Side note: Should we consider making it a cron-job so that it can be run at a more reasonable time?

**Comment by timothyhuo1** [comment]
Review Branch: https://github.com/radgrad/radgrad2/tree/review-702-timothy

Plan to run scrapers with InternAloha and import the resulting JSON file into RadGrad. 

Similar to Students, we should have an Internship Manage page. Here is where the admin can upload Internship data (similar to STAR?) and an option to add or edit internships manually. 

During this process of importing data, we should address duplicates and assign Interests and Career Goals to the internships which are noted in the I[nternshipCollection.method.ts](https://github.com/radgrad/radgrad2/blob/review-702-timothy/app/imports/api/internship/InternshipCollection.methods.ts) file.

**Comment by CalianaFortin** [comment]
Review Branch: https://github.com/radgrad/radgrad2/tree/review-702-caliana

Basically my plan relies on a JSON file being uploaded. The functions related to sorting and eliminating duplicates can be found here https://github.com/radgrad/radgrad2/blob/review-702-caliana/app/imports/api/internship/InternshipCollection.methods.ts . Maybe before eliminating the duplicate internships the Admin could view the all the duplicated internships to check and make sure it can be eliminated.

**Comment by saitoshi** [comment]
<a href = "https://github.com/radgrad/radgrad2/tree/review-702-shun">Review Branch</a>
My idea was combining ideas from other collections and creating new ideas which relies on the JSON file being uploaded. 
<ul>
<li>Internship Manage Page: Admin can upload intership data and an option to either add a new internship or edit already uploaded internship.</li>
<li>Duplicate Check: Checks whether the internship already exists to avoid any duplicates.</li>
<li>Assignment: For each internship created it should find related interests and career goal (possiblly courses but this could be difficult).</li>
</ul>
